<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Destination;
use Illuminate\Database\Seeder;

class MoroccoDataSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'Nature' => 'Natural landscapes, mountains, waterfalls and deserts.',
            'Historical Sites' => 'Ancient medinas, kasbahs and monuments.',
            'Beaches' => 'Coastal towns and Atlantic/Mediterranean beaches.',
            'Cultural Places' => 'Museums, souks and traditional experiences.',
        ];

        $categoryIds = [];
        foreach ($categories as $name => $description) {
            $category = Category::firstOrCreate(['name' => $name], ['description' => $description]);
            $categoryIds[$name] = $category->id;
        }

        $destinations = [
            [
                'category' => 'Historical Sites',
                'name' => 'Chefchaouen (The Blue City)',
                'description' => 'Famous for its striking blue-washed buildings nestled in the Rif Mountains, Chefchaouen is one of the most photographed towns in Morocco.',
                'city' => 'Chefchaouen',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.1688,
                'longitude' => -5.2636,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Jemaa el-Fnaa',
                'description' => 'The bustling main square of Marrakech, alive with storytellers, musicians, food stalls and snake charmers. A UNESCO-recognized cultural space.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6258,
                'longitude' => -7.9891,
            ],
            [
                'category' => 'Nature',
                'name' => 'Ouzoud Waterfalls',
                'description' => 'Located in the Béni Mellal-Khénifra region, the Ouzoud Waterfalls are one of Morocco\'s most popular natural attractions, cascading over 100 meters.',
                'city' => 'Azilal',
                'region' => 'Béni Mellal-Khénifra',
                'latitude' => 32.0044,
                'longitude' => -6.7208,
            ],
            [
                'category' => 'Nature',
                'name' => 'Merzouga & Erg Chebbi Dunes',
                'description' => 'Golden Sahara sand dunes reaching up to 150 meters high, famous for camel treks and overnight desert camps under the stars.',
                'city' => 'Merzouga',
                'region' => 'Drâa-Tafilalet',
                'latitude' => 31.0801,
                'longitude' => -4.0133,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Essaouira Beach & Medina',
                'description' => 'A windswept coastal city known for its fortified medina, fishing port, and popular surfing and kitesurfing beaches.',
                'city' => 'Essaouira',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.5085,
                'longitude' => -9.7595,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Fes el Bali (Old Medina)',
                'description' => 'The largest car-free urban area in the world, home to ancient tanneries, madrasas, and the University of Al Quaraouiyine, the oldest in the world.',
                'city' => 'Fes',
                'region' => 'Fès-Meknès',
                'latitude' => 34.0667,
                'longitude' => -4.9833,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Hassan II Mosque',
                'description' => 'One of the largest mosques in the world, built partly over the Atlantic Ocean, featuring the tallest minaret on Earth at 210 meters.',
                'city' => 'Casablanca',
                'region' => 'Casablanca-Settat',
                'latitude' => 33.6086,
                'longitude' => -7.6326,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Legzira Beach',
                'description' => 'Famous for its striking natural rock arches carved into red sandstone cliffs along the Atlantic coast near Sidi Ifni.',
                'city' => 'Sidi Ifni',
                'region' => 'Guelmim-Oued Noun',
                'latitude' => 29.5833,
                'longitude' => -10.1000,
            ],
                        [
                'category' => 'Beaches',
                'name' => 'Legzira Beach',
                'description' => 'Famous for its striking natural rock arches carved into red sandstone cliffs along the Atlantic coast near Sidi Ifni.',
                'city' => 'Sidi Ifni',
                'region' => 'Guelmim-Oued Noun',
                'latitude' => 29.5833,
                'longitude' => -10.1000,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Volubilis Roman Ruins',
                'description' => 'A UNESCO World Heritage site featuring the best-preserved Roman ruins in Morocco, including mosaics, columns, and a triumphal arch.',
                'city' => 'Meknes',
                'region' => 'Fès-Meknès',
                'latitude' => 34.0742,
                'longitude' => -5.5548,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Majorelle Garden',
                'description' => 'A stunning botanical garden in Marrakech, once owned by Yves Saint Laurent, filled with cacti, cobalt-blue buildings and exotic plants.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6412,
                'longitude' => -8.0031,
            ],
            [
                'category' => 'Nature',
                'name' => 'Todra Gorge',
                'description' => 'Spectacular limestone canyon walls rising up to 300 meters, popular for hiking, rock climbing and scenic drives.',
                'city' => 'Tinghir',
                'region' => 'Drâa-Tafilalet',
                'latitude' => 31.5825,
                'longitude' => -5.5806,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Ait Benhaddou Kasbah',
                'description' => 'A fortified earthen village (ksar) along the former caravan route, famous as a filming location for movies like Gladiator and Game of Thrones.',
                'city' => 'Ouarzazate',
                'region' => 'Drâa-Tafilalet',
                'latitude' => 31.0472,
                'longitude' => -7.1319,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Taghazout',
                'description' => 'A laid-back surfing village on the Atlantic coast, popular with surfers of all levels and known for its relaxed vibe and beach cafés.',
                'city' => 'Taghazout',
                'region' => 'Souss-Massa',
                'latitude' => 30.5445,
                'longitude' => -9.7098,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Rick\'s Café',
                'description' => 'A restaurant and piano bar in Casablanca inspired by the film Casablanca, recreating the ambiance of 1940s Morocco.',
                'city' => 'Casablanca',
                'region' => 'Casablanca-Settat',
                'latitude' => 33.6031,
                'longitude' => -7.6186,
            ],
            [
                'category' => 'Nature',
                'name' => 'Ifrane National Park',
                'description' => 'Known as "Little Switzerland," this Middle Atlas town is famous for its Alpine-style architecture, cedar forests, and Barbary macaques.',
                'city' => 'Ifrane',
                'region' => 'Fès-Meknès',
                'latitude' => 33.5228,
                'longitude' => -5.1106,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Kasbah of the Udayas',
                'description' => 'A UNESCO-listed 12th-century fortress overlooking the Bou Regreg river, featuring a picturesque blue-and-white medina and Andalusian gardens.',
                'city' => 'Rabat',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.0331,
                'longitude' => -6.8351,
            ],
                        [
                'category' => 'Beaches',
                'name' => 'Asilah',
                'description' => 'A charming coastal town known for its whitewashed medina walls covered in colorful murals, created during the annual Asilah Arts Festival.',
                'city' => 'Asilah',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.4650,
                'longitude' => -6.0339,
            ],
            [
                'category' => 'Nature',
                'name' => 'Paradise Valley',
                'description' => 'A lush oasis near Agadir featuring natural rock pools, waterfalls and palm groves, popular for swimming and canyoning.',
                'city' => 'Agadir',
                'region' => 'Souss-Massa',
                'latitude' => 30.6167,
                'longitude' => -9.5333,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Bahia Palace',
                'description' => 'A 19th-century palace in Marrakech renowned for its intricate stucco work, carved cedar ceilings, and beautifully landscaped courtyards.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6215,
                'longitude' => -7.9827,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Meknes Bab Mansour',
                'description' => 'One of the most beautiful gates in Morocco, marking the entrance to the imperial city of Meknes, adorned with intricate zellige tilework.',
                'city' => 'Meknes',
                'region' => 'Fès-Meknès',
                'latitude' => 33.8935,
                'longitude' => -5.5547,
            ],
            [
                'category' => 'Nature',
                'name' => 'Toubkal National Park',
                'description' => 'Home to Jebel Toubkal, the highest peak in North Africa at 4,167 meters, a major destination for hikers and mountaineers in the High Atlas.',
                'city' => 'Imlil',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.0595,
                'longitude' => -7.9152,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Oualidia Lagoon',
                'description' => 'A tranquil coastal town famous for its calm lagoon, oyster farms, and gentle waves, ideal for families and seafood lovers.',
                'city' => 'Oualidia',
                'region' => 'Casablanca-Settat',
                'latitude' => 32.7358,
                'longitude' => -9.0333,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Tangier Kasbah Museum',
                'description' => 'Perched above the Strait of Gibraltar, Tangier blends Mediterranean and Atlantic influences with a rich literary and artistic history.',
                'city' => 'Tangier',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.7595,
                'longitude' => -5.8340,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Chellah Necropolis',
                'description' => 'A medieval fortified necropolis in Rabat built on the ruins of the ancient Roman city of Sala Colonia, now home to storks and lush gardens.',
                'city' => 'Rabat',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.0092,
                'longitude' => -6.8228,
            ],
            [
                'category' => 'Nature',
                'name' => 'Dades Valley (Valley of a Thousand Kasbahs)',
                'description' => 'A dramatic valley of rose-colored kasbahs, winding roads and rock formations resembling human figures, between Ouarzazate and the desert.',
                'city' => 'Boumalne Dades',
                'region' => 'Drâa-Tafilalet',
                'latitude' => 31.3833,
                'longitude' => -5.9833,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Al Hoceima National Park',
                'description' => 'A coastal park on the Mediterranean with turquoise waters, dramatic cliffs and hidden coves, less touristy than Atlantic beach towns.',
                'city' => 'Al Hoceima',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.2517,
                'longitude' => -3.9317,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'El Jadida Portuguese Cistern',
                'description' => 'A UNESCO-listed 16th-century Portuguese fortified city featuring an atmospheric underground cistern famously filmed by Orson Welles.',
                'city' => 'El Jadida',
                'region' => 'Casablanca-Settat',
                'latitude' => 33.2547,
                'longitude' => -8.5058,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Ouzoud Berber Villages',
                'description' => 'Traditional Amazigh (Berber) villages surrounding the Ouzoud waterfalls, offering authentic crafts, mint tea and mountain hospitality.',
                'city' => 'Azilal',
                'region' => 'Béni Mellal-Khénifra',
                'latitude' => 31.9917,
                'longitude' => -6.7167,
            ],
            [
                'category' => 'Nature',
                'name' => 'Tafraoute & the Painted Rocks',
                'description' => 'A pink granite valley in the Anti-Atlas mountains, famous for surreal boulders painted blue by a Belgian artist and traditional almond groves.',
                'city' => 'Tafraoute',
                'region' => 'Souss-Massa',
                'latitude' => 29.7167,
                'longitude' => -8.9667,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Dakhla Lagoon',
                'description' => 'A remote Saharan peninsula famous for world-class kitesurfing and windsurfing, with turquoise lagoon waters meeting golden desert dunes.',
                'city' => 'Dakhla',
                'region' => 'Dakhla-Oued Ed-Dahab',
                'latitude' => 23.7185,
                'longitude' => -15.9370,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Marrakech Koutoubia Mosque',
                'description' => 'The largest mosque in Marrakech, its 12th-century minaret served as the prototype for the Giralda in Seville and the Hassan Tower in Rabat.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6238,
                'longitude' => -7.9934,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Marrakech Souks',
                'description' => 'A vast maze of traditional markets selling spices, leather goods, lanterns, carpets and ceramics, a sensory highlight of any Marrakech visit.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6295,
                'longitude' => -7.9836,
            ],
            [
                'category' => 'Nature',
                'name' => 'Cascades d\'Akchour',
                'description' => 'Hidden waterfalls and natural rock bridges in the Talassemtane National Park near Chefchaouen, reached by a scenic riverside hike.',
                'city' => 'Chefchaouen',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.2833,
                'longitude' => -5.1667,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Meknes Heri es-Souani Granaries',
                'description' => 'Massive 17th-century royal granaries and stables built by Sultan Moulay Ismail to store grain and house thousands of horses.',
                'city' => 'Meknes',
                'region' => 'Fès-Meknès',
                'latitude' => 33.8894,
                'longitude' => -5.5581,
            ],
            [
                'category' => 'Nature',
                'name' => 'Zaouiat Ahansal',
                'description' => 'A remote High Atlas village surrounded by dramatic canyons and cliffs, a hidden gem for trekkers and rock climbers.',
                'city' => 'Azilal',
                'region' => 'Béni Mellal-Khénifra',
                'latitude' => 31.9333,
                'longitude' => -6.4333,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Sidi Kaouki',
                'description' => 'A quiet, windswept beach village near Essaouira, favored by windsurfers and travelers seeking a laid-back alternative to busier resorts.',
                'city' => 'Essaouira',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.3833,
                'longitude' => -9.8333,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Chefchaouen Kasbah Museum',
                'description' => 'A small ethnographic museum inside a 15th-century kasbah in the heart of Chefchaouen, with gardens and views over the blue medina.',
                'city' => 'Chefchaouen',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.1714,
                'longitude' => -5.2697,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Rabat Hassan Tower',
                'description' => 'The unfinished minaret of a 12th-century mosque, standing alongside the Mausoleum of Mohammed V, both symbols of Rabat.',
                'city' => 'Rabat',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.0242,
                'longitude' => -6.8228,
            ],
            [
                'category' => 'Nature',
                'name' => 'Lalla Takerkoust Lake',
                'description' => 'A scenic artificial lake near Marrakech at the foot of the Atlas Mountains, popular for boating, quad biking and lakeside lunches.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.3667,
                'longitude' => -8.2167,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Mehdia Beach',
                'description' => 'A popular Atlantic beach near a 17th-century Portuguese-Spanish fortress, close to Kenitra and easily reached from Rabat.',
                'city' => 'Kenitra',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.2667,
                'longitude' => -6.6667,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Tetouan Medina',
                'description' => 'A UNESCO World Heritage medina blending Andalusian and Moroccan architecture, known for its craftsmanship and white-washed houses.',
                'city' => 'Tetouan',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.5711,
                'longitude' => -5.3724,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Marrakech Saadian Tombs',
                'description' => 'A 16th-century royal necropolis rediscovered in 1917, renowned for its elaborate marble decoration and Chamber of the Twelve Columns.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6178,
                'longitude' => -7.9893,
            ],
            [
                'category' => 'Nature',
                'name' => 'Ouzoud to Bin El Ouidane Lake',
                'description' => 'A turquoise reservoir lake in the Atlas foothills, framed by mountains, popular for water sports and scenic drives from Ouzoud.',
                'city' => 'Beni Mellal',
                'region' => 'Béni Mellal-Khénifra',
                'latitude' => 32.1167,
                'longitude' => -6.4667,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Cabo Negro',
                'description' => 'An upscale Mediterranean resort beach near Tetouan, known for golf courses, marinas and calm turquoise waters.',
                'city' => 'Martil',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.6333,
                'longitude' => -5.3167,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Fes Chouara Tannery',
                'description' => 'One of the oldest leather tanneries in the world, where hides are still dyed by hand in stone vessels using traditional methods.',
                'city' => 'Fes',
                'region' => 'Fès-Meknès',
                'latitude' => 34.0669,
                'longitude' => -4.9722,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Marrakech City Walls',
                'description' => 'Nearly 19 kilometers of ochre-colored ramparts encircling the old medina, built in the 12th century and still remarkably intact.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6300,
                'longitude' => -7.9700,
            ],
            [
                'category' => 'Nature',
                'name' => 'Talassemtane National Park',
                'description' => 'A protected mountain park near Chefchaouen with cedar and fir forests, home to the endangered Barbary macaque.',
                'city' => 'Chefchaouen',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.2333,
                'longitude' => -5.1167,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Imsouane',
                'description' => 'A small fishing village turned surf destination, famous for one of the longest right-hand waves in the world.',
                'city' => 'Imsouane',
                'region' => 'Marrakech-Safi',
                'latitude' => 30.8500,
                'longitude' => -9.8167,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Ben Youssef Madrasa',
                'description' => 'A former Islamic college in Marrakech, celebrated for its stunning zellige tilework, carved stucco and central courtyard.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6314,
                'longitude' => -7.9891,
            ],
            [
                'category' => 'Nature',
                'name' => 'Ouirgane Valley',
                'description' => 'A peaceful valley in the High Atlas foothills, dotted with walnut and olive groves, ideal for gentle hiking and mountain retreats.',
                'city' => 'Ouirgane',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.2833,
                'longitude' => -8.1500,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Fes Bab Boujloud',
                'description' => 'The ornate blue and green tiled gate marking the main entrance to Fes el Bali, one of the most photographed landmarks in the city.',
                'city' => 'Fes',
                'region' => 'Fès-Meknès',
                'latitude' => 34.0644,
                'longitude' => -4.9797,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Plage Blanche (Guelmim)',
                'description' => 'A vast, remote stretch of white sand near the edge of the Sahara, largely untouched by mass tourism.',
                'city' => 'Guelmim',
                'region' => 'Guelmim-Oued Noun',
                'latitude' => 28.6167,
                'longitude' => -11.0000,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Marrakech Museum',
                'description' => 'Housed in the restored 19th-century Dar Mnebhi Palace, showcasing Moroccan art, ceramics, textiles and calligraphy.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6308,
                'longitude' => -7.9885,
            ],
            [
                'category' => 'Nature',
                'name' => 'Cirque de Jaffar',
                'description' => 'A dramatic mountain circuit near Midelt in the Middle Atlas, offering panoramic views, cedar forests and scenic 4x4 routes.',
                'city' => 'Midelt',
                'region' => 'Drâa-Tafilalet',
                'latitude' => 32.6833,
                'longitude' => -4.7333,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Taroudant City Walls',
                'description' => 'Often called "Grandmother of Marrakech," Taroudant is encircled by well-preserved red pisé walls dating to the 16th century.',
                'city' => 'Taroudant',
                'region' => 'Souss-Massa',
                'latitude' => 30.4703,
                'longitude' => -8.8770,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Agadir Beach & Marina',
                'description' => 'A modern seaside city with a long sandy beach, palm-lined promenade, and lively marina rebuilt after the 1960 earthquake.',
                'city' => 'Agadir',
                'region' => 'Souss-Massa',
                'latitude' => 30.4202,
                'longitude' => -9.5981,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Essaouira Skala de la Ville',
                'description' => 'A fortified sea bastion with rows of bronze cannons overlooking the Atlantic, famously featured in Game of Thrones.',
                'city' => 'Essaouira',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.5147,
                'longitude' => -9.7702,
            ],
            [
                'category' => 'Nature',
                'name' => 'Aguelmame Azigza Lake',
                'description' => 'A remote natural lake in the Middle Atlas surrounded by cedar forests, popular for camping, fishing and birdwatching.',
                'city' => 'Khenifra',
                'region' => 'Béni Mellal-Khénifra',
                'latitude' => 32.9167,
                'longitude' => -5.2333,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Chefchaouen Ras El Maa',
                'description' => 'A natural spring and waterfall at the edge of the Chefchaouen medina, historically used as a communal laundry and gathering spot.',
                'city' => 'Chefchaouen',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.1725,
                'longitude' => -5.2611,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Moulay Bousselham',
                'description' => 'A coastal lagoon town and important wetland reserve, renowned for birdwatching, especially flamingos and migratory species.',
                'city' => 'Moulay Bousselham',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.8833,
                'longitude' => -6.2833,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Meknes Dar Jamai Museum',
                'description' => 'A 19th-century palace turned museum in Meknes, displaying traditional Moroccan crafts, carpets, ceramics and jewelry.',
                'city' => 'Meknes',
                'region' => 'Fès-Meknès',
                'latitude' => 33.8956,
                'longitude' => -5.5497,
            ],
            [
                'category' => 'Nature',
                'name' => 'Sources of Oum Er-Rbia',
                'description' => 'A dramatic series of natural springs cascading down cliffs near Khenifra, believed by locals to have healing properties.',
                'city' => 'Khenifra',
                'region' => 'Béni Mellal-Khénifra',
                'latitude' => 32.9500,
                'longitude' => -5.6667,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Marrakech El Badi Palace',
                'description' => 'The ruins of a once-opulent 16th-century palace, now home to nesting storks, occasional exhibitions and panoramic rooftop views.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6167,
                'longitude' => -7.9853,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Boujdour Coastline',
                'description' => 'A quiet Atlantic Saharan town with rugged cliffs, a historic lighthouse and long uncrowded beaches.',
                'city' => 'Boujdour',
                'region' => 'Laâyoune-Sakia El Hamra',
                'latitude' => 26.1258,
                'longitude' => -14.4850,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Ouarzazate Atlas Film Studios',
                'description' => 'One of the largest film studios in the world, where blockbusters like Lawrence of Arabia and Gladiator were filmed against desert backdrops.',
                'city' => 'Ouarzazate',
                'region' => 'Drâa-Tafilalet',
                'latitude' => 30.9500,
                'longitude' => -6.9333,
            ],
            [
                'category' => 'Nature',
                'name' => 'Jbel Saghro',
                'description' => 'A rugged, arid mountain range south of the High Atlas, popular for multi-day trekking through remote Berber villages.',
                'city' => 'Nekob',
                'region' => 'Drâa-Tafilalet',
                'latitude' => 31.0333,
                'longitude' => -5.8333,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Safi Portuguese Fortress',
                'description' => 'A 16th-century Portuguese citadel overlooking the Atlantic, part of Safi\'s historic old town, famous for pottery and ceramics.',
                'city' => 'Safi',
                'region' => 'Marrakech-Safi',
                'latitude' => 32.2994,
                'longitude' => -9.2372,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Cala Iris',
                'description' => 'A hidden cove near Al Hoceima with turquoise Mediterranean water and dramatic cliffs, popular with local divers and snorkelers.',
                'city' => 'Al Hoceima',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.1667,
                'longitude' => -4.3667,
            ],
            [
                'category' => 'Nature',
                'name' => 'Ourika Valley',
                'description' => 'A green valley in the High Atlas foothills near Marrakech, dotted with Berber villages, walnut trees, and small waterfalls popular for day trips.',
                'city' => 'Ourika',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.3167,
                'longitude' => -7.6667,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Meknes Mausoleum of Moulay Ismail',
                'description' => 'The ornate final resting place of Sultan Moulay Ismail, one of the few mosque-mausoleums in Morocco open to non-Muslim visitors.',
                'city' => 'Meknes',
                'region' => 'Fès-Meknès',
                'latitude' => 33.8947,
                'longitude' => -5.5486,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Rabat Andalusian Gardens',
                'description' => 'Tranquil gardens within the Kasbah of the Udayas, blending Andalusian and Moroccan landscaping with citrus trees and fountains.',
                'city' => 'Rabat',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.0347,
                'longitude' => -6.8364,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Sidi Bouzid Beach',
                'description' => 'A popular family beach near El Jadida with calm waters, seaside cafés and dramatic cliffside views of the Portuguese fortress.',
                'city' => 'El Jadida',
                'region' => 'Casablanca-Settat',
                'latitude' => 33.2333,
                'longitude' => -8.5333,
            ],
            [
                'category' => 'Nature',
                'name' => 'Beni Mellal Ain Asserdoun',
                'description' => 'A hillside garden and spring near Beni Mellal, popular for picnics with cascading water features and views over the Tadla plain.',
                'city' => 'Beni Mellal',
                'region' => 'Béni Mellal-Khénifra',
                'latitude' => 32.3450,
                'longitude' => -6.3500,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Larache Lixus Ruins',
                'description' => 'Ancient Phoenician and Roman ruins overlooking the Loukkos River estuary, among the oldest archaeological sites on the Atlantic coast.',
                'city' => 'Larache',
                'region' => 'Tanger-Tetouan-Al Hoceima',
                'latitude' => 35.2167,
                'longitude' => -6.1167,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Marrakech Maison de la Photographie',
                'description' => 'A museum showcasing rare vintage photographs of Morocco from 1870 to 1950, housed in a restored riad with a rooftop café.',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.6304,
                'longitude' => -7.9838,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Tan-Tan Plage',
                'description' => 'A remote southern beach town near the edge of the Sahara, known for its wide sandy shores and traditional Moussem festival.',
                'city' => 'Tan-Tan',
                'region' => 'Guelmim-Oued Noun',
                'latitude' => 28.4833,
                'longitude' => -11.3333,
            ],
            [
                'category' => 'Nature',
                'name' => 'Immouzer des Ida Outanane',
                'description' => 'A mountain town near Agadir famous for its waterfalls, honey production, and scenic gorges in the western High Atlas.',
                'city' => 'Immouzer',
                'region' => 'Souss-Massa',
                'latitude' => 30.7833,
                'longitude' => -9.3333,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Azemmour Medina',
                'description' => 'A small, less-visited fortified medina on the Oum Er-Rbia River, known for its Portuguese ramparts and vibrant street art.',
                'city' => 'Azemmour',
                'region' => 'Casablanca-Settat',
                'latitude' => 33.2892,
                'longitude' => -8.3419,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Fes Nejjarine Museum',
                'description' => 'A museum of wood arts and crafts housed in a restored 18th-century caravanserai (fondouk) in the heart of Fes el Bali.',
                'city' => 'Fes',
                'region' => 'Fès-Meknès',
                'latitude' => 34.0631,
                'longitude' => -4.9764,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Plage des Nations',
                'description' => 'A wide sandy beach north of Rabat known for consistent waves, popular with surf schools and weekend visitors from the capital.',
                'city' => 'Salé',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.1167,
                'longitude' => -6.7167,
            ],
            [
                'category' => 'Nature',
                'name' => 'Ain Leuh Cedar Forest',
                'description' => 'A Middle Atlas cedar forest near Azrou, home to some of the oldest cedar trees in Morocco and troops of Barbary macaques.',
                'city' => 'Azrou',
                'region' => 'Fès-Meknès',
                'latitude' => 33.4333,
                'longitude' => -5.2167,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Ksar of Tinghir',
                'description' => 'A traditional fortified earthen village near the entrance to Todra Gorge, showcasing classic Berber pisé architecture.',
                'city' => 'Tinghir',
                'region' => 'Drâa-Tafilalet',
                'latitude' => 31.5150,
                'longitude' => -5.5333,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Essaouira Wood Workshops',
                'description' => 'Traditional artisan workshops near the port where craftsmen carve fragrant thuya wood into boxes, chess sets and furniture.',
                'city' => 'Essaouira',
                'region' => 'Marrakech-Safi',
                'latitude' => 31.5131,
                'longitude' => -9.7699,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Sables d\'Or (Mohammedia)',
                'description' => 'A popular golden sand beach in Mohammedia near Casablanca, lined with cafés, a marina and a historic Portuguese fortress.',
                'city' => 'Mohammedia',
                'region' => 'Casablanca-Settat',
                'latitude' => 33.7167,
                'longitude' => -7.3833,
            ],
            [
                'category' => 'Nature',
                'name' => 'Jebel Sirwa',
                'description' => 'A volcanic peak in the Anti-Atlas mountains offering multi-day treks through remote Berber villages and terraced valleys.',
                'city' => 'Taliouine',
                'region' => 'Souss-Massa',
                'latitude' => 30.5167,
                'longitude' => -7.6167,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Rabat Archaeological Museum',
                'description' => 'Home to Morocco\'s finest collection of Roman bronzes and artifacts excavated from Volubilis and other ancient sites.',
                'city' => 'Rabat',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.0181,
                'longitude' => -6.8347,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Taliouine Saffron Cooperatives',
                'description' => 'The saffron capital of Morocco, where visitors can tour cooperatives and learn about the harvesting of the world\'s most expensive spice.',
                'city' => 'Taliouine',
                'region' => 'Souss-Massa',
                'latitude' => 30.5333,
                'longitude' => -7.9167,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Sidi Rahal Beach',
                'description' => 'A quieter Atlantic beach between Casablanca and El Jadida, popular with local families and known for its rocky coves.',
                'city' => 'Sidi Rahal',
                'region' => 'Casablanca-Settat',
                'latitude' => 33.0167,
                'longitude' => -8.0000,
            ],
            [
                'category' => 'Nature',
                'name' => 'Amtoudi Oasis',
                'description' => 'A remote Anti-Atlas oasis with an ancient fortified granary (agadir) perched on a cliff overlooking date palm groves.',
                'city' => 'Amtoudi',
                'region' => 'Guelmim-Oued Noun',
                'latitude' => 29.4667,
                'longitude' => -9.1833,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Sale Great Mosque and Medina',
                'description' => 'A historic sister-city to Rabat across the Bou Regreg river, with a well-preserved medina, mosque and traditional souks.',
                'city' => 'Salé',
                'region' => 'Rabat-Salé-Kénitra',
                'latitude' => 34.0453,
                'longitude' => -6.8264,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Khouribga Phosphate Museum',
                'description' => 'A museum dedicated to Morocco\'s phosphate mining heritage, one of the country\'s most important industries and export sectors.',
                'city' => 'Khouribga',
                'region' => 'Béni Mellal-Khénifra',
                'latitude' => 32.8811,
                'longitude' => -6.9063,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Kariat Arkmane Lagoon',
                'description' => 'A protected Mediterranean lagoon near Nador, known for its birdlife, calm waters and traditional fishing villages.',
                'city' => 'Nador',
                'region' => 'Oriental',
                'latitude' => 35.1833,
                'longitude' => -2.8333,
            ],
            [
                'category' => 'Nature',
                'name' => 'Oujda Sidi Yahya Oasis',
                'description' => 'A green oasis just outside Oujda in eastern Morocco, home to a shrine, palm groves and freshwater springs.',
                'city' => 'Oujda',
                'region' => 'Oriental',
                'latitude' => 34.7167,
                'longitude' => -1.8667,
            ],
            [
                'category' => 'Historical Sites',
                'name' => 'Oujda Old Medina',
                'description' => 'A historic walled city near the Algerian border with a preserved medina, ramparts and a blend of Amazigh and Andalusian heritage.',
                'city' => 'Oujda',
                'region' => 'Oriental',
                'latitude' => 34.6867,
                'longitude' => -1.9114,
            ],
            [
                'category' => 'Cultural Places',
                'name' => 'Safi Pottery Cooperatives',
                'description' => 'Morocco\'s ceramics capital, where visitors can watch artisans hand-throw and paint the country\'s famous blue-green pottery.',
                'city' => 'Safi',
                'region' => 'Marrakech-Safi',
                'latitude' => 32.2833,
                'longitude' => -9.2333,
            ],
            [
                'category' => 'Beaches',
                'name' => 'Ras Kebdana',
                'description' => 'A quiet Mediterranean fishing village near the Algerian border, with unspoiled beaches and traditional boat-building.',
                'city' => 'Ras Kebdana',
                'region' => 'Oriental',
                'latitude' => 35.1500,
                'longitude' => -2.3667,
            ],
            [
                'category' => 'Nature',
                'name' => 'Debdou Forest',
                'description' => 'A little-visited mountain town in eastern Morocco surrounded by cedar and oak forests, historically home to a diverse Jewish-Amazigh community.',
                'city' => 'Debdou',
                'region' => 'Oriental',
                'latitude' => 33.9833,
                'longitude' => -3.0333,
            ],
        ];

        foreach ($destinations as $data) {
            Destination::firstOrCreate(
                ['name' => $data['name']],
                [
                    'category_id' => $categoryIds[$data['category']],
                    'description' => $data['description'],
                    'city' => $data['city'],
                    'region' => $data['region'],
                    'latitude' => $data['latitude'],
                    'longitude' => $data['longitude'],
                    'status' => 'published',
                ]
            );
        }
    }
}
